address: 0.0.0.0
port: ${oc.decode:${oc.env:PORT, 5000}}
websocket_origin: "*"
xheaders: true
verbose: false
open: false
static_dirs:
  webfonts: ./data_lunch_app/static/fontawesome/webfonts
  images: ./data_lunch_app/static/images
compress_response: true