version: "3.9"
services:
  web:
    image: malberti/data-lunch-app
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.web
    volumes:
      - ./shared_data:/app/shared_data
    expose:
      - "5000" # Expose port 5000 to an ephemeral port (used by load balancer)
    environment:
      PANEL_ENV: development
      PORT: 5000
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000" # port 4000 available on localhost
networks:
  default:
    driver: bridge
    name: data-lunch
