version: "3.9"
services:
  web:
    image: michelealberti/data-lunch-app
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile.web
    volumes:
      - ./shared_data:/app/shared_data
    expose:
      - "5000" # Expose port 5000 to an ephemeral port (used by load balancer)
    environment:
      PANEL_APP: data-lunch-app
      PANEL_ENV: production
      PORT: 5000
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - web
    ports:
      - "443:443" # port 443 available on localhost
      - "80:80" # port 80 available on localhost
networks:
  default:
    driver: bridge
    name: data-lunch
