shared_data_folder: ${oc.env:PANEL_SHARED_DATA_FOLDER, shared_data}
name: lunch
url: sqlite:///${db.shared_data_folder}/${db.name}.db
engine:
  _target_: sqlalchemy.create_engine
  url: ${db.url}
menu_table: menu
