shared_data_folder: ${oc.env:PANEL_SHARED_DATA_FOLDER, /tmp/shared_data}
name: lunch
url: sqlite:///${db.shared_data_folder}/${db.name}.db
engine:
  _target_: sqlalchemy.create_engine
  url: ${db.url}
menu_table: menu
orders_query: "
  SELECT o.id, o.user, o.lunch_time, m.item
  FROM orders o
  LEFT JOIN menu m
  ON m.id = o.menu_item_id ;
  "
