defaults:
  - _self_ #configs from the Defaults List are overriding config.yaml
  - panel: default
  - db: ${oc.env:PANEL_ENV}
  - server: ${oc.env:PANEL_ENV}
  - override hydra/job_logging: custom
#  - _self_ #config.yaml is overriding configs from the Defaults List

# LOCAL TIMEZONE
local_timezone: Europe/Rome

hydra:
  # disable changing of cwd as it interferes with flask auto-restart
  run:
    dir: .
  # output files creation
  output_subdir: null
