defaults:
  - default

# TAKEAWAY LUNCHES
takeaway_alert_icon_options: 'class="fa-solid fa-jedi fa-fade fa-sm" style="--fa-animation-duration: 1.5s;"'

# CUSTOMIZABLE GRAPHIC OBJECTS
# Instantiate a panel object to be rendered on app's header
# Set to null to ignore
# e.g: _target_: panel.pane.HTML with _args_: - <img src="${panel.favicon_path}"> 
header_object:
  _target_: panel.pane.HTML
  _convert_: all
  _args_:
    - <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Star_Wars_Day_May_The_Fourth.svg/1920px-Star_Wars_Day_May_The_Fourth.svg.png" height="100%" width="auto">
  height: 50